package com.ap0n.headache.ui

import androidx.compose.foundation.layout.padding
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.remember
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import com.ap0n.headache.domain.model.HeadacheEntry
import com.ap0n.headache.domain.model.QuestionType
import com.ap0n.headache.domain.model.WizardQuestion

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddHeadacheScreen(
    viewModel: MainViewModel,
    onNavigateBack: () -> Unit
) {
    val questions by viewModel.wizardQuestions.collectAsState()

    // Create a "Dummy" empty headache to start with
    val defaultHeadache = remember {
        HeadacheEntry(
            id = "", // Will be generated by ViewModel on save
            timestamp = System.currentTimeMillis(),
            severity = 5,
            durationMinutes = 60,
            notes = ""
        )
    }

    // Calculate Default Answers once when questions load
    // This ensures every field has a value, so the user can just click "Save"
    val defaultAnswers = remember(questions) {
        questions.associate { q ->
            q.id to getDefaultValue(q)
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("New Entry") }
            )
        }
    ) { padding ->
        // Reuse the form we built for Editing!
        EditForm(
            initialHeadache = defaultHeadache,
            initialFactors = defaultAnswers,
            questions = questions,
            onSave = { severity, notes, factors ->
                viewModel.saveHeadache(severity, 60, notes, factors)
                onNavigateBack()
            },
            modifier = Modifier.padding(padding)
        )
    }
}

// Helper to pick sensible defaults based on question type
private fun getDefaultValue(q: WizardQuestion): Any {
    return when (q.type) {
        QuestionType.NUMERIC -> q.min ?: 0f
        QuestionType.BOOLEAN -> false
        QuestionType.SINGLE_CHOICE -> q.options.firstOrNull() ?: ""
        QuestionType.TEXT -> ""
    }
}